name: Build linux image

on: [workflow_call]

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Build
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest-ubuntu ./linux
    - name: Export
      run: |
        docker save -o /tmp/image_ubuntu.tar ${{ env.IMAGE_NAME }}:latest-ubuntu
    - name: Cache docker image
      run: |
        curl -X POST -F "file=@/tmp/image_ubuntu.tar" -F "project_id=gha-runner" -F "issue_id=1" http://192.168.0.11:25000/dump
    - name: Remove local image
      run: |
        docker image rm ${{ env.IMAGE_NAME }}:latest-ubuntu
